server:
  port: 80

spring:
  application:
    name: cloud-consumer-order

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka #集群版
      #defaultZone: http://localhost:7001/eureka
    #是否将自己注册到eureka 默认true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息 默认为true
    fetch-registry: true