server:
  port: 7002

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
    fetch-registry: true
  instance:
    hostname: eureka7002.com
