server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  zipkin:
      base-url: http://localhost:9411
    sleuth:
      sampler:
      #采样率介于0~1之间，1表示全部采集  # 将采样比例设置为 1.0，也就是全部都需要。默认是 0.1
      probability: 1
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    #当前数锯源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver
    #mysqL驱动包
    url: jdbc:mysql://localhost:3306/db2020?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root123456

mybatis:
  mapperLocations: classpath:mapper/*.xml
  #所有Entity别名类所在包
  type-aliases-package: com.atguigu.springcloud.entities

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka #集群版
      # defaultZone: http://localhost:7001/eureka 单机版
    #是否将自己注册到eureka 默认true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息 默认为true
    fetch-registry: true
#    eureka-server-connect-timeout-seconds:
#    eureka-server-d-n-s-name:
#    eureka-server-port:
  #主机规范名称 在注册中心服务的名称
  instance:
    instance-id: payment8001
    prefer-ip-address: true # 鼠标放置在名称上有ip提示:







