server:
  port: 7001

eureka:
  instance:
    hostname: eureka7001.com
    #hostname: localhost #eureka 服务的端的实例名称（单机）
  client:
    #表示不向服务中心注册自己
    register-with-eureka: true
    #维护服务实例 不进行检索服务
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka #集群版 相互注册 7001注册7002
      # 设置与Eureka Server交互的地址 查询服务和注册服务都需要这个地址
      # defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ 单机版


  #server:
      #关闭自我保护机制，保证不可用服务被及时踢除,默认发心跳时间2000ms=2s 2s内没心跳就删掉微服务的信息
      #enable-self-preservation: false
      #eviction-interval-timer-in-ms: 2000